nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        paths:
            /api/login_check:
              post:
                tags:
                  - Login
                summary: Se connecter et récupérer un token.
                requestBody:
                  description: Identifiants
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          username:
                            type: string
                            example: bouygues@example.com
                          password:
                            type: string
                            example: secret
                responses:
                  '200':
                    description: Retourne un token
                    content:
                      application/json:
                        schema:
                          type: object
                          properties:
                            token:
                              type: string
                  '401':
                    description: Identifiants incorrects
                    content:
                      application/json:
                        schema:
                          type: object
                          properties:
                            code:
                              type: int
                              example: 401
                            message:
                              type: string
                              example: Invalid credentials

    areas:
        path_patterns:
            - ^/api(?!/doc)
